#!/usr/bin/env bash

usage() {
    echo "usage: $0 [-h] [-n top_n] trigger-name [trigger-name ...]"
}

OPTIND=1
top_n="${TOP_N:-0}"

while getopts "hn:" opt; do {
    case "$opt" in
        h) usage; exit 0;;
        n) top_n="$OPTARG";;
        *) usage; exit 1;;
    esac
}; done

shift $((OPTIND-1))

[ -z "$1" ] && {
    usage
    exit 1
}

[ -z "$STATUS_VIEW_ONCE" ] && {
    export STATUS_VIEW_ONCE=1
    export TOP_N="$top_n"
    watch -tn1 "$0" "$@"
    exit 0
}

records="`sed 1d "$1"`"

shift 1
for t in "$@"; do
    printf 'trigger %s\n' "$t"

    t_head=host
    t_records="`grep "^$t,0," <<< "$records" | sort -nr -k5,6 -t, | awk -F, '{print $4 " " $5 / 1000000 " " $6 / 1000000 " " $7 / 1000 " " $8 / 1000 " " $5 / $7 / 8 " " $6 / $8 / 8}'`"
    [ -z "$t_records" ] && {
        t_records="`grep "^$t,1," <<< "$records" | sort -nr -k5,6 -t, | awk -F, '{print $4 " " $5 / 1000000 " " $6 / 1000000 " " $7 / 1000 " " $8 / 1000 " " $5 / $7 / 8 " " $6 / $8 / 8}'`"
        t_head=net
    }
    [ "$top_n" -gt 0 ] && {
        t_records="`<<< "$t_records" head -n "$top_n"`"
    }
    addr_len="`cut -d' ' -f1 <<< "$t_records" | wc -L`"

    [ -z "$t_records" ] && {
        t_head="???"
        t_records="<no-flows>"
        addr_len=10
    }

    printf "  %-${addr_len}s %8s %8s %8s %8s %8s %8s\n" $t_head in_mbps out_mbps in_kpps out_kpps in_sz out_sz
    printf "  %-${addr_len}s %8.2f %8.2f %8.2f %8.2f %8.0f %8.0f\n" $t_records
    printf '\n'
done

