#!/usr/bin/env bash

[ -z "$2" ] && {
    echo "usage: $0 <status-file> <trigger-name>"
    exit 1
}

[ -z "$STATUS_VIEW_ONCE" ] && {
    export STATUS_VIEW_ONCE=1
    watch -tn1 "$0" "$1" "$2"
}

records="`sed 1d "$1"`"
t_records="`grep "^$2," <<< "$records" | sort -nr -k4,5 -t, | awk -F, '{print $3 " " $4 / 1000000 " " $5 / 1000000 " " $6 " " $7}'`"
addr_len="`cut -d' ' -f1 <<< "$t_records" | wc -L`"

[ -z "$t_records" ] && {
    t_records="<no-flows>"
    addr_len=10
}

printf "%-${addr_len}s %8s %8s %12s %12s\n" host in_mbps out_mbps in_pps out_pps
printf "%-${addr_len}s %8.2f %8.2f %12u %12u\n" $t_records